name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # または master ブランチ

# リポジトリへの書き込み権限を設定
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: Build
        run: npm run build -- --base-href=/AngularDemo/

      - name: Create .nojekyll file
        run: touch dist/angular-test/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-test
          branch: gh-pages
          token: ${{ github.token }}
