name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # または master ブランチ

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --base-href=/AngularPageDemo/
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/angular-test  # angular.jsonのoutputPathに合わせる
          branch: gh-pages
